language: go

go:
  - tip

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/golang.org/x"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/jakub-gawlas/oauth2-fork"
  - go get -v -t -d github.com/jakub-gawlas/oauth2-fork/...

script:
  - go test -v github.com/jakub-gawlas/oauth2-fork/...
